name: patg.net 
markdown: redcarpet
pygments: true
#baseurl: /
permalink: pretty
paginate: 10
url: http://patg.net
#markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
